using Microsoft.AspNetCore.Mvc;
using MongoDB.Driver;
using MongoDB.Bson;
using InventoryService.Data;

namespace InventoryService.Controllers
{
    /// <summary>
    /// Serves ML price predictions generated by the Python pipeline.
    /// Python writes to MongoDB → this controller reads and exposes via REST.
    /// </summary>
    [ApiController]
    [Route("predictions")]
    public class PredictionsController : ControllerBase
    {
        private readonly MongoDbContext _db;
        public PredictionsController(MongoDbContext db) => _db = db;

        // GET /predictions/{flightId}?daysLeft=7&class=economy
        [HttpGet("{flightId}")]
        public async Task<ActionResult> GetPrediction(
            string flightId,
            [FromQuery] int daysLeft   = 7,
            [FromQuery] string @class  = "economy")
        {
            var col = _db.Database.GetCollection<BsonDocument>("price_predictions");

            // Find closest available days_left
            var candidates = await col
                .Find(Builders<BsonDocument>.Filter.And(
                    Builders<BsonDocument>.Filter.Eq("flightId", flightId),
                    Builders<BsonDocument>.Filter.Eq("seatClass", @class)))
                .ToListAsync();

            if (!candidates.Any())
                return NotFound(new { message = "No predictions available. Run python_pipeline/price_prediction.py first." });

            // Pick nearest days_left
            var best = candidates
                .OrderBy(d => Math.Abs(d["daysLeft"].AsInt32 - daysLeft))
                .First();

            return Ok(new
            {
                flightId      = best["flightId"].AsString,
                flightNumber  = best["flightNumber"].AsString,
                route         = best["route"].AsString,
                daysLeft      = best["daysLeft"].AsInt32,
                seatClass     = best["seatClass"].AsString,
                xgbPrice      = best["xgbPrice"].AsInt32,
                lgbmPrice     = best["lgbmPrice"].AsInt32,
                ensemblePrice = best["ensemblePrice"].AsInt32,
                actualFare    = best["actualFare"].AsInt32,
                priceDiff     = best["ensemblePrice"].AsInt32 - best["actualFare"].AsInt32,
            });
        }

        // GET /predictions/route?from=DEL&to=BOM&class=economy
        [HttpGet("route")]
        public async Task<ActionResult> GetRouteForecasts(
            [FromQuery] string from,
            [FromQuery] string to,
            [FromQuery] string @class = "economy")
        {
            var col = _db.Database.GetCollection<BsonDocument>("price_predictions");

            var route = $"{from?.ToUpper()}→{to?.ToUpper()}";
            var docs  = await col
                .Find(Builders<BsonDocument>.Filter.And(
                    Builders<BsonDocument>.Filter.Eq("route", route),
                    Builders<BsonDocument>.Filter.Eq("seatClass", @class)))
                .SortBy(d => d["daysLeft"])
                .ToListAsync();

            if (!docs.Any())
                return NotFound(new { message = $"No predictions for {route}. Run the Python pipeline first." });

            var forecast = docs.Select(d => new
            {
                flightId      = d["flightId"].AsString,
                flightNumber  = d["flightNumber"].AsString,
                daysLeft      = d["daysLeft"].AsInt32,
                xgbPrice      = d["xgbPrice"].AsInt32,
                lgbmPrice     = d["lgbmPrice"].AsInt32,
                ensemblePrice = d["ensemblePrice"].AsInt32,
                actualFare    = d["actualFare"].AsInt32,
            }).ToList();

            return Ok(new { route, seatClass = @class, forecast });
        }

        // GET /predictions/metrics  — model performance summary
        [HttpGet("metrics")]
        public async Task<ActionResult> GetMetrics()
        {
            var col = _db.Database.GetCollection<BsonDocument>("ml_model_metrics");
            var doc = await col
                .Find(FilterDefinition<BsonDocument>.Empty)
                .SortByDescending(d => d["generatedAt"])
                .FirstOrDefaultAsync();

            if (doc == null)
                return NotFound(new { message = "No model metrics found. Run price_prediction.py first." });

            return Ok(doc.ToJson());
        }
    }
}
